// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cam

import (
	"github.com/Havens-blog/e-cam-service/internal/cam/repository"
	"github.com/Havens-blog/e-cam-service/internal/cam/repository/dao"
	"github.com/Havens-blog/e-cam-service/internal/cam/service"
	"github.com/Havens-blog/e-cam-service/internal/cam/sync/service/adapters"
	"github.com/Havens-blog/e-cam-service/internal/cam/task"
	service2 "github.com/Havens-blog/e-cam-service/internal/cam/task/service"
	web2 "github.com/Havens-blog/e-cam-service/internal/cam/task/web"
	"github.com/Havens-blog/e-cam-service/internal/cam/web"
	"github.com/Havens-blog/e-cam-service/pkg/mongox"
	"github.com/Havens-blog/e-cam-service/pkg/taskx"
	"github.com/google/wire"
	"github.com/gotomicro/ego/core/elog"
	"sync"
)

// Injectors from wire.go:

// InitModule 初始化CAM模块
func InitModule(db *mongox.Mongo) (*Module, error) {
	assetDAO := InitAssetDAO(db)
	assetRepository := repository.NewAssetRepository(assetDAO)
	cloudAccountDAO := InitCloudAccountDAO(db)
	cloudAccountRepository := repository.NewCloudAccountRepository(cloudAccountDAO)
	component := ProvideLogger()
	adapterFactory := adapters.NewAdapterFactory(component)
	serviceService := service.NewService(assetRepository, cloudAccountRepository, adapterFactory, component)
	cloudAccountService := service.NewCloudAccountService(cloudAccountRepository, component)
	modelDAO := InitModelDAO(db)
	modelRepository := repository.NewModelRepository(modelDAO)
	modelFieldDAO := InitModelFieldDAO(db)
	modelFieldRepository := repository.NewModelFieldRepository(modelFieldDAO)
	modelFieldGroupDAO := InitModelFieldGroupDAO(db)
	modelFieldGroupRepository := repository.NewModelFieldGroupRepository(modelFieldGroupDAO)
	modelService := service.NewModelService(modelRepository, modelFieldRepository, modelFieldGroupRepository)
	handler := web.NewHandler(serviceService, cloudAccountService, modelService)
	module, err := task.InitModule(db, serviceService, component)
	if err != nil {
		return nil, err
	}
	queue := module.Queue
	taskRepository := InitTaskRepository(db)
	taskService := service2.NewTaskService(queue, taskRepository, component)
	taskHandler := web2.NewTaskHandler(taskService)
	camModule := &Module{
		Hdl:        handler,
		Svc:        serviceService,
		AccountSvc: cloudAccountService,
		ModelSvc:   modelService,
		TaskModule: module,
		TaskSvc:    taskService,
		TaskHdl:    taskHandler,
	}
	return camModule, nil
}

// wire.go:

var (
	camInitOnce sync.Once
)

// InitCollectionOnce 初始化数据库集合和索引（只执行一次）
func InitCollectionOnce(db *mongox.Mongo) {
	camInitOnce.Do(func() {

		if err := dao.InitIndexes(db); err != nil {
			panic("failed to init cam indexes: " + err.Error())
		}
	})
}

// InitAssetDAO 初始化资产DAO
func InitAssetDAO(db *mongox.Mongo) dao.AssetDAO {
	InitCollectionOnce(db)
	return dao.NewAssetDAO(db)
}

// InitCloudAccountDAO 初始化云账号DAO
func InitCloudAccountDAO(db *mongox.Mongo) dao.CloudAccountDAO {
	InitCollectionOnce(db)
	return dao.NewCloudAccountDAO(db)
}

// InitModelDAO 初始化模型DAO
func InitModelDAO(db *mongox.Mongo) dao.ModelDAO {
	InitCollectionOnce(db)
	return dao.NewModelDAO(db)
}

// InitModelFieldDAO 初始化字段DAO
func InitModelFieldDAO(db *mongox.Mongo) dao.ModelFieldDAO {
	InitCollectionOnce(db)
	return dao.NewModelFieldDAO(db)
}

// InitModelFieldGroupDAO 初始化字段分组DAO
func InitModelFieldGroupDAO(db *mongox.Mongo) dao.ModelFieldGroupDAO {
	InitCollectionOnce(db)
	return dao.NewModelFieldGroupDAO(db)
}

// InitTaskRepository 初始化任务仓储
func InitTaskRepository(db *mongox.Mongo) taskx.TaskRepository {
	return taskx.NewMongoRepository(db, "tasks")
}

// ProviderSet Wire依赖注入集合
var ProviderSet = wire.NewSet(

	InitAssetDAO,
	InitCloudAccountDAO,
	InitModelDAO,
	InitModelFieldDAO,
	InitModelFieldGroupDAO, repository.NewAssetRepository, repository.NewCloudAccountRepository, repository.NewModelRepository, repository.NewModelFieldRepository, repository.NewModelFieldGroupRepository, InitTaskRepository, adapters.NewAdapterFactory, service.NewService, service.NewCloudAccountService, service.NewModelService, task.InitModule, wire.FieldsOf(new(*task.Module), "Queue"), service2.NewTaskService, web2.NewTaskHandler, ProvideLogger, web.NewHandler, wire.Struct(new(Module), "Hdl", "Svc", "AccountSvc", "ModelSvc", "TaskModule", "TaskSvc", "TaskHdl"),
)

// ProvideLogger 提供默认logger
func ProvideLogger() *elog.Component {
	return elog.DefaultLogger
}
