// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cam

import (
	"github.com/Havens-blog/e-cam-service/internal/cam/repository"
	"github.com/Havens-blog/e-cam-service/internal/cam/repository/dao"
	"github.com/Havens-blog/e-cam-service/internal/cam/service"
	"github.com/Havens-blog/e-cam-service/internal/cam/web"
	"github.com/Havens-blog/e-cam-service/pkg/mongox"
	"github.com/google/wire"
	"github.com/gotomicro/ego/core/elog"
	"sync"
)

// Injectors from wire.go:

// InitModule 初始化CAM模块
func InitModule(db *mongox.Mongo) (*Module, error) {
	assetDAO := InitAssetDAO(db)
	assetRepository := repository.NewAssetRepository(assetDAO)
	serviceService := service.NewService(assetRepository)
	cloudAccountDAO := InitCloudAccountDAO(db)
	cloudAccountRepository := repository.NewCloudAccountRepository(cloudAccountDAO)
	component := ProvideLogger()
	cloudAccountService := service.NewCloudAccountService(cloudAccountRepository, component)
	v := web.NewHandler(serviceService, cloudAccountService)
	module := &Module{
		Hdl:        v,
		Svc:        serviceService,
		AccountSvc: cloudAccountService,
	}
	return module, nil
}

// wire.go:

var (
	camInitOnce sync.Once
)

// InitCollectionOnce 初始化数据库集合和索引（只执行一次）
func InitCollectionOnce(db *mongox.Mongo) {
	camInitOnce.Do(func() {

		if err := dao.InitIndexes(db); err != nil {
			panic("failed to init cam indexes: " + err.Error())
		}
	})
}

// InitAssetDAO 初始化资产DAO
func InitAssetDAO(db *mongox.Mongo) dao.AssetDAO {
	InitCollectionOnce(db)
	return dao.NewAssetDAO(db)
}

// InitCloudAccountDAO 初始化云账号DAO
func InitCloudAccountDAO(db *mongox.Mongo) dao.CloudAccountDAO {
	InitCollectionOnce(db)
	return dao.NewCloudAccountDAO(db)
}

// ProviderSet Wire依赖注入集合
var ProviderSet = wire.NewSet(

	InitAssetDAO,
	InitCloudAccountDAO, repository.NewAssetRepository, repository.NewCloudAccountRepository, service.NewService, service.NewCloudAccountService, ProvideLogger, web.NewHandler, wire.Struct(new(Module), "*"),
)

// ProvideLogger 提供默认logger
func ProvideLogger() *elog.Component {
	return elog.DefaultLogger
}
