// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ioc

import (
	"github.com/Havens-blog/e-cam-service/internal/cam"
	"github.com/Havens-blog/e-cam-service/internal/endpoint"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitApp() (*App, error) {
	cmdable := InitRedis()
	provider := InitSessionProvider(cmdable)
	v := InitGinMiddlewares()
	server := InitGrpcServer()
	v2 := InitJobs()
	mongo := InitMongoDB()
	endpointModule, err := endpoint.InitModule(mongo)
	if err != nil {
		return nil, err
	}
	endpointService := endpointModule.Svc
	endpointHandler := endpointModule.Hdl
	camModule, err := cam.InitModule(mongo)
	if err != nil {
		return nil, err
	}
	camService := camModule.Svc
	camHandler := camModule.Hdl
	engine := InitWebServer(provider, v, endpointHandler, camHandler)
	app := &App{
		Web:    engine,
		Grpc:   server,
		Jobs:   v2,
		EndSvc: endpointService,
		CamSvc: camService,
	}
	return app, nil
}

// wire.go:

var BaseSet = wire.NewSet(
	InitMongoDB,
	InitRedis,
	InitGrpcServer,
	InitSessionProvider,
	InitGinMiddlewares,
	InitWebServer,
	InitJobs,
	endpoint.InitModule,
	cam.InitModule,
	wire.FieldsOf(new(*endpoint.Module), "Hdl", "Svc"),
	wire.FieldsOf(new(*cam.Module), "Hdl", "Svc"),
)
