// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ioc

import (
	"github.com/Havens-blog/e-cam-service/internal/cam"
	"github.com/Havens-blog/e-cam-service/internal/cmdb"
	"github.com/Havens-blog/e-cam-service/internal/endpoint"
	"github.com/google/wire"
)

import (
	_ "github.com/Havens-blog/e-cam-service/docs"
)

// Injectors from wire.go:

func InitApp() (*App, error) {
	logger := InitLogger()
	cmdable := InitRedis()
	provider := InitSessionProvider(cmdable)
	v := InitGinMiddlewares()
	mongo := InitMongoDB()
	module, err := endpoint.InitModule(mongo)
	if err != nil {
		return nil, err
	}
	v2 := module.Hdl
	camModule, err := cam.InitModuleWithIAM(mongo)
	if err != nil {
		return nil, err
	}
	cmdbModule := cmdb.InitModule(mongo)
	engine := InitWebServer(provider, v, v2, camModule, cmdbModule)
	server := InitGrpcServer()
	v3 := InitJobs()
	app := &App{
		Logger:    logger,
		Web:       engine,
		Grpc:      server,
		Jobs:      v3,
		EndModule: module,
		CamModule: camModule,
	}
	return app, nil
}

// wire.go:

var BaseSet = wire.NewSet(
	InitLogger,
	InitMongoDB,
	InitRedis,
	InitGrpcServer,
	InitSessionProvider,
	InitGinMiddlewares,
	InitWebServer,
	InitJobs, endpoint.InitModule, cam.InitModuleWithIAM, cmdb.InitModule, wire.FieldsOf(new(*endpoint.Module), "Hdl"), wire.FieldsOf(new(*cam.Module), "Hdl", "TaskHdl"),
)
