// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject

package ioc

import (
	"github.com/Havens-blog/e-cam-service/internal/cam"
	"github.com/Havens-blog/e-cam-service/internal/cmdb"
	"github.com/Havens-blog/e-cam-service/internal/endpoint"
	"github.com/google/wire"

	_ "github.com/Havens-blog/e-cam-service/docs"
)

// Injectors from wire.go:

func InitApp() (*App, error) {
	logger := InitLogger()
	cmdable := InitRedis()
	provider := InitSessionProvider(cmdable)
	v := InitGinMiddlewares()
	client := InitEtcdClient()
	policyServiceClient := InitEcmdbPolicyClient(client)
	checkPolicyMiddleware := InitCheckPolicyMiddleware(policyServiceClient)
	mongo := InitMongoDB()
	module := InitAuditModule(mongo)
	auditMiddleware := InitAuditMiddleware(module)
	endpointServiceClient := InitEcmdbEndpointClient(client)
	endpointModule, err := endpoint.InitModule(mongo)
	if err != nil {
		return nil, err
	}
	v2 := endpointModule.Hdl
	alertModule := InitAlertModule(mongo)
	camModule, err := cam.InitModuleWithIAM(mongo, cmdable, alertModule)
	if err != nil {
		return nil, err
	}
	cmdbModule := cmdb.InitModule(mongo)
	engine := InitWebServer(provider, v, checkPolicyMiddleware, auditMiddleware, module, endpointServiceClient, v2, camModule, cmdbModule, alertModule, mongo)
	server := InitGrpcServer(client)
	v3 := InitJobs(camModule)
	app := &App{
		Logger:    logger,
		Web:       engine,
		Grpc:      server,
		Jobs:      v3,
		EndModule: endpointModule,
		CamModule: camModule,
	}
	return app, nil
}

// wire.go:

var BaseSet = wire.NewSet(
	InitLogger,
	InitMongoDB,
	InitRedis,
	InitGrpcServer,
	InitSessionProvider,
	InitGinMiddlewares,
	InitEtcdClient,
	InitEcmdbPolicyClient,
	InitEcmdbEndpointClient,
	InitCheckPolicyMiddleware,
	InitAuditModule,
	InitAuditMiddleware,
	InitWebServer,
	InitJobs,
	endpoint.InitModule,
	cam.InitModuleWithIAM,
	cmdb.InitModule,
	InitAlertModule,
	wire.FieldsOf(new(*endpoint.Module), "Hdl"),
	wire.FieldsOf(new(*cam.Module), "Hdl", "TaskHdl"),
)
