// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package iam

import (
	"github.com/Havens-blog/e-cam-service/internal/cam/iam/repository"
	"github.com/Havens-blog/e-cam-service/internal/cam/iam/repository/dao"
	"github.com/Havens-blog/e-cam-service/internal/cam/iam/service"
	"github.com/Havens-blog/e-cam-service/internal/cam/iam/web"
	repository2 "github.com/Havens-blog/e-cam-service/internal/cam/repository"
	dao2 "github.com/Havens-blog/e-cam-service/internal/cam/repository/dao"
	"github.com/Havens-blog/e-cam-service/internal/shared/cloudx/iam"
	"github.com/Havens-blog/e-cam-service/pkg/mongox"
	"github.com/google/wire"
	"github.com/gotomicro/ego/core/elog"
	"sync"
)

// Injectors from wire.go:

// InitModule 初始化IAM模块
func InitModule(db *mongox.Mongo) (*Module, error) {
	cloudUserDAO := InitCloudUserDAO(db)
	cloudUserRepository := repository.NewCloudUserRepository(cloudUserDAO)
	userGroupDAO := InitUserGroupDAO(db)
	userGroupRepository := repository.NewUserGroupRepository(userGroupDAO)
	syncTaskDAO := InitSyncTaskDAO(db)
	syncTaskRepository := repository.NewSyncTaskRepository(syncTaskDAO)
	cloudAccountRepository := InitCloudAccountRepository(db)
	component := ProvideLogger()
	cloudIAMAdapterFactory := iam.New(component)
	cloudUserService := service.NewCloudUserService(cloudUserRepository, userGroupRepository, syncTaskRepository, cloudAccountRepository, cloudIAMAdapterFactory, component)
	userHandler := web.NewUserHandler(cloudUserService, component)
	auditLogDAO := InitAuditLogDAO(db)
	auditLogRepository := repository.NewAuditLogRepository(auditLogDAO)
	userGroupService := service.NewUserGroupService(userGroupRepository, cloudUserRepository, syncTaskRepository, auditLogRepository, cloudAccountRepository, cloudIAMAdapterFactory, component)
	userGroupHandler := web.NewUserGroupHandler(userGroupService, component)
	permissionService := service.NewPermissionService(cloudUserRepository, userGroupRepository, cloudAccountRepository, cloudIAMAdapterFactory, component)
	permissionHandler := web.NewPermissionHandler(permissionService, component)
	syncService := service.NewSyncService(syncTaskRepository, cloudUserRepository, userGroupRepository, cloudAccountRepository, cloudIAMAdapterFactory, component)
	syncHandler := web.NewSyncHandler(syncService, component)
	auditService := service.NewAuditService(auditLogRepository, component)
	auditHandler := web.NewAuditHandler(auditService, component)
	policyTemplateDAO := InitPolicyTemplateDAO(db)
	policyTemplateRepository := repository.NewPolicyTemplateRepository(policyTemplateDAO)
	policyTemplateService := service.NewPolicyTemplateService(policyTemplateRepository, userGroupRepository, component)
	templateHandler := web.NewTemplateHandler(policyTemplateService, component)
	tenantDAO := InitTenantDAO(db)
	tenantRepository := repository.NewTenantRepository(tenantDAO)
	tenantService := service.NewTenantService(tenantRepository, cloudAccountRepository, cloudUserRepository, userGroupRepository, component)
	tenantHandler := web.NewTenantHandler(tenantService, component)
	module := &Module{
		UserHandler:       userHandler,
		GroupHandler:      userGroupHandler,
		PermissionHandler: permissionHandler,
		SyncHandler:       syncHandler,
		AuditHandler:      auditHandler,
		TemplateHandler:   templateHandler,
		TenantHandler:     tenantHandler,
	}
	return module, nil
}

// wire.go:

var (
	iamInitOnce sync.Once
)

// InitCollectionOnce 初始化数据库集合和索引（只执行一次）
func InitCollectionOnce(db *mongox.Mongo) {
	iamInitOnce.Do(func() {

		if err := dao.InitIndexes(db); err != nil {
			panic("failed to init iam indexes: " + err.Error())
		}
	})
}

// InitCloudUserDAO 初始化用户DAO
func InitCloudUserDAO(db *mongox.Mongo) dao.CloudUserDAO {
	InitCollectionOnce(db)
	return dao.NewCloudUserDAO(db)
}

// InitUserGroupDAO 初始化用户组DAO
func InitUserGroupDAO(db *mongox.Mongo) dao.UserGroupDAO {
	InitCollectionOnce(db)
	return dao.NewUserGroupDAO(db)
}

// InitSyncTaskDAO 初始化同步任务DAO
func InitSyncTaskDAO(db *mongox.Mongo) dao.SyncTaskDAO {
	InitCollectionOnce(db)
	return dao.NewSyncTaskDAO(db)
}

// InitAuditLogDAO 初始化审计日志DAO
func InitAuditLogDAO(db *mongox.Mongo) dao.AuditLogDAO {
	InitCollectionOnce(db)
	return dao.NewAuditLogDAO(db)
}

// InitPolicyTemplateDAO 初始化策略模板DAO
func InitPolicyTemplateDAO(db *mongox.Mongo) dao.PolicyTemplateDAO {
	InitCollectionOnce(db)
	return dao.NewPolicyTemplateDAO(db)
}

// InitTenantDAO 初始化租户DAO
func InitTenantDAO(db *mongox.Mongo) dao.TenantDAO {
	InitCollectionOnce(db)
	return dao.NewTenantDAO(db)
}

// InitCloudAccountRepository 初始化云账号Repository（从CAM模块）
func InitCloudAccountRepository(db *mongox.Mongo) repository2.CloudAccountRepository {

	camdao := dao2.NewCloudAccountDAO(db)
	return repository2.NewCloudAccountRepository(camdao)
}

// ProviderSet Wire依赖注入集合
var ProviderSet = wire.NewSet(

	InitCloudUserDAO,
	InitUserGroupDAO,
	InitSyncTaskDAO,
	InitAuditLogDAO,
	InitPolicyTemplateDAO,
	InitTenantDAO, repository.NewCloudUserRepository, repository.NewUserGroupRepository, repository.NewSyncTaskRepository, repository.NewAuditLogRepository, repository.NewPolicyTemplateRepository, repository.NewTenantRepository, InitCloudAccountRepository, iam.New, service.NewCloudUserService, service.NewUserGroupService, service.NewPermissionService, service.NewSyncService, service.NewAuditService, service.NewPolicyTemplateService, service.NewTenantService, ProvideLogger, web.NewUserHandler, web.NewUserGroupHandler, web.NewPermissionHandler, web.NewSyncHandler, web.NewAuditHandler, web.NewTemplateHandler, web.NewTenantHandler, wire.Struct(new(Module), "*"),
)

// ProvideLogger 提供默认logger
func ProvideLogger() *elog.Component {
	return elog.DefaultLogger
}
