// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package servicetree

import (
	"github.com/Havens-blog/e-cam-service/internal/cam/repository"
	"github.com/Havens-blog/e-cam-service/internal/cam/servicetree/adapter"
	"github.com/Havens-blog/e-cam-service/internal/cam/servicetree/port"
	repository3 "github.com/Havens-blog/e-cam-service/internal/cam/servicetree/repository"
	"github.com/Havens-blog/e-cam-service/internal/cam/servicetree/repository/dao"
	"github.com/Havens-blog/e-cam-service/internal/cam/servicetree/service"
	"github.com/Havens-blog/e-cam-service/internal/cam/servicetree/web"
	repository2 "github.com/Havens-blog/e-cam-service/internal/cmdb/repository"
	"github.com/Havens-blog/e-common-go/mongox"
	"github.com/google/wire"
	"github.com/gotomicro/ego/core/elog"
)

// Injectors from wire.go:

// InitModule 初始化服务树模块
// instanceRepo 从 cam 模块注入，用于规则引擎查询实例
// cmdbRepo 从 cmdb 模块注入，通过 adapter 转换为 port.CMDBPort
func InitModule(db *mongox.Mongo, instanceRepo repository.InstanceRepository, cmdbRepo repository2.InstanceRepository, logger *elog.Component) (*Module, error) {
	nodeDAO := dao.NewNodeDAO(db)
	nodeRepository := repository3.NewNodeRepository(nodeDAO)
	bindingDAO := dao.NewBindingDAO(db)
	bindingRepository := repository3.NewBindingRepository(bindingDAO)
	treeService := service.NewTreeService(nodeRepository, bindingRepository, logger)
	bindingService := service.NewBindingService(bindingRepository, nodeRepository, logger)
	ruleDAO := dao.NewRuleDAO(db)
	ruleRepository := repository3.NewRuleRepository(ruleDAO)
	environmentDAO := dao.NewEnvironmentDAO(db)
	environmentRepository := repository3.NewEnvironmentRepository(environmentDAO)
	ruleEngineService := service.NewRuleEngineService(ruleRepository, bindingRepository, nodeRepository, instanceRepo, environmentRepository, logger)
	localCMDBAdapter := adapter.NewLocalCMDBAdapter(cmdbRepo)
	nodeAssetService := service.NewNodeAssetService(bindingRepository, nodeRepository, localCMDBAdapter, environmentRepository, logger)
	handler := web.NewHandler(treeService, bindingService, ruleEngineService, nodeAssetService)
	environmentService := service.NewEnvironmentService(environmentRepository, bindingRepository, logger)
	envHandler := web.NewEnvHandler(environmentService)
	module := NewModule(handler, envHandler, treeService, bindingService, ruleEngineService, environmentService, nodeAssetService)
	return module, nil
}

// wire.go:

// ProviderSet 服务树模块依赖注入集合
var ProviderSet = wire.NewSet(dao.NewNodeDAO, dao.NewBindingDAO, dao.NewRuleDAO, dao.NewEnvironmentDAO, repository3.NewNodeRepository, repository3.NewBindingRepository, repository3.NewRuleRepository, repository3.NewEnvironmentRepository, adapter.NewLocalCMDBAdapter, wire.Bind(new(port.CMDBPort), new(*adapter.LocalCMDBAdapter)), service.NewTreeService, service.NewBindingService, service.NewRuleEngineService, service.NewEnvironmentService, service.NewNodeAssetService, web.NewHandler, web.NewEnvHandler)
