// @feature cert-multicloud-deployers @api-functional
//
// Contract: multicloud-cert-replacement / Step 3 — 上传段——证书上传至各云证书库.
// Outcomes under test: success, upload-rate-limited-retry, crash-before-bind-recovery.
//
// SKIP_EVAL_GATE: generated without eval-contract verification. Review with
// extra scrutiny.

package multicloud_cert_replacement

import (
	"context"
	"testing"

	"github.com/Havens-blog/e-cam-service/internal/cert/domain"
	"github.com/Havens-blog/e-cam-service/internal/shared/cloudx"
	"github.com/Havens-blog/e-cam-service/tests/multicloudtest"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// oneCloudWorld seeds a minimal single-item ( huawei cdn ) replacement world.
func oneCloudWorld(t *testing.T, h *multicloudtest.Harness) (replacementWorld, multicloudtest.ChangeListPayload) {
	t.Helper()
	w := replacementWorld{Domain: "www.example.com"}
	w.OldCertID, w.OldFP = h.SeedCompleteCert("old.example.com", w.Domain)
	w.NewCertID, w.NewFP = h.SeedCompleteCert("new.example.com", w.Domain)
	w.OldCloudIDs = map[string]string{"huawei": "scm-old-cert-0001"}
	h.OldCertCloudID("huawei", w.OldCloudIDs["huawei"], w.OldFP)
	w.SnapshotID = h.SeedDoneSnapshotWithRefs([]multicloudtest.RefSpec{
		{Cloud: domain.CloudHuawei, Product: domain.ProductCDN, AccountKey: "acct-hw-1",
			ResourceID: "www.example.com", CloudCertID: w.OldCloudIDs["huawei"], Fingerprint: w.OldFP},
	})
	list := generateFor(t, h, w)
	require.Len(t, list.Items, 1)
	return w, list
}

// Contract outcome "success": UploadCert 将新证书（证书链+私钥）上传至云证书库，
// 返回云证书 ID；上传成功后映射先行写入 active；私钥明文仅内存传递。
// NOTE: the deployer rejects empty material, so a successful two-phase run
// proves the ledger material ( cert chain + decrypted key ) reached the cloud.
func TestExecuteUploadPhase_UploadsMaterialAndWritesMapping(t *testing.T) {
	h := multicloudtest.NewHarness(t, nil)
	w, list := oneCloudWorld(t, h)

	h.MustConfirm(list.OrderID, nil)
	h.MustExecute(list.OrderID)

	// Upload happened exactly once for the single item.
	uploads := h.Huawei.UploadCalls()
	require.Len(t, uploads, 1, "one upload call per item: %v", uploads)
	assert.True(t, len(uploads[0]) > len("cdn:"), "upload name generated by the single-point formula")

	// Deep (cross-entity): 上传返回的云证书 ID 落入映射与条目，三者一致。
	item, err := h.Items.GetByID(context.Background(), list.Items[0].ItemID)
	require.NoError(t, err)
	assert.Equal(t, domain.ItemStatusSuccess, item.Status)
	require.NotEmpty(t, item.NewCloudCertID)
	mapping, err := h.MappingByCloudCert("huawei", "acct-hw-1", item.NewCloudCertID)
	require.NoError(t, err, "mapping row exists for the uploaded cloud cert ID")
	assert.Equal(t, domain.MappingStatusActive, mapping.Status, "mapping written active (crash-recovery anchor)")
	assert.Equal(t, w.NewFP, mapping.CertFingerprint)
	require.NotNil(t, mapping.UploadedAt, "uploadedAt defaulted to now")

	// State: 云证书 ID 进入执行上下文（绑定段使用同一条 ID）。
	binds := h.Huawei.BindCalls()
	require.Len(t, binds, 1)
	assert.Contains(t, binds[0], item.NewCloudCertID, "bind consumed the uploaded cloud cert ID")
}

// Contract outcome "upload-rate-limited-retry": 云侧限流 → 部署器有界退避自动
// 重试，每次重试生成新上传名称不复用旧名称；重试成功条目收敛 success。
// NOTE: the engine-level rate_limited marking ( 30s/2m real backoff sequence )
// is out of hermetic scope — this test exercises the deployer-level bounded
// retry seam ( same RetryPolicy shape, millisecond backoffs ) and the
// new-name-per-attempt guarantee ( C7: retry is a new copy ).
func TestExecuteUploadPhase_RateLimitedRetriesWithNewName(t *testing.T) {
	h := multicloudtest.NewHarness(t, nil)
	w, list := oneCloudWorld(t, h)

	// First upload call rate-limited, second succeeds ( within the bounded
	// retry policy: 3 attempts, millisecond backoffs ).
	h.Huawei.SetUploadErr(1, cloudx.ErrCloudRateLimited)

	h.MustConfirm(list.OrderID, nil)
	h.MustExecute(list.OrderID)

	// Output: 限流消耗一次重试后成功；每次尝试新上传名称。
	uploads := h.Huawei.UploadCalls()
	require.Len(t, uploads, 2, "bounded retry consumed exactly one extra attempt: %v", uploads)
	assert.NotEqual(t, uploads[0], uploads[1],
		"retry generates a new upload name ( never reuses the possibly-consumed name )")

	// State: 条目 success；映射以最终上传产物写入 active。
	item, err := h.Items.GetByID(context.Background(), list.Items[0].ItemID)
	require.NoError(t, err)
	assert.Equal(t, domain.ItemStatusSuccess, item.Status)
	mapping, err := h.MappingByCloudCert("huawei", "acct-hw-1", item.NewCloudCertID)
	require.NoError(t, err)
	assert.Equal(t, domain.MappingStatusActive, mapping.Status)
	assert.Equal(t, w.NewFP, mapping.CertFingerprint)
}

// Contract outcome "crash-before-bind-recovery": 心跳超时恢复将条目标记
// failed(EXEC_TIMEOUT)；重跑重新走两段式上传新副本，按映射唯一键覆盖旧记录。
func TestExecuteUploadPhase_CrashBeforeBindRecoveredByTimeout(t *testing.T) {
	h := multicloudtest.NewHarness(t, nil)
	w := replacementWorld{Domain: "www.example.com"}
	w.OldCertID, w.OldFP = h.SeedCompleteCert("old.example.com", w.Domain)
	w.NewCertID, w.NewFP = h.SeedCompleteCert("new.example.com", w.Domain)

	orderID := h.SeedOrder(domain.ChangeStatusExecuting, seededBatchInfo(1), nil, w.OldFP, w.NewCertID)
	ref := domain.ResourceRef{Channel: domain.ChannelCloudAPI, Cloud: "huawei",
		Product: "cdn", AccountKey: "acct-hw-1", ResourceID: "www.example.com"}
	itemID := seedTimedOutItem(t, h, orderID, ref, w.OldCloudIDs["huawei"])

	// Shrink the verify window so the recovered order can be finalized to a
	// terminal state by the window-expiry job ( frees the active mutex for
	// the rerun order — verifying orders keep holding the old-fingerprint
	// token and cannot be re-generated against ).
	cfg, cfgErr := h.AlertCfg.Get(context.Background())
	require.NoError(t, cfgErr)
	cfg.Thresholds.VerifyWindowHours = 0
	require.NoError(t, h.AlertCfg.Save(context.Background(), &cfg))

	// Crash anchor: the upload succeeded pre-crash, mapping already active.
	firstUploadID := "scm-orphan-first-copy"
	h.SeedMapping(w.NewFP, "huawei", "acct-hw-1", firstUploadID)

	// 恢复链路（生产入口 cert:executing-timeout 调度任务）。
	recovered, err := h.Exec.RecoverTimedOutItems(context.Background())
	require.NoError(t, err)
	assert.Equal(t, 1, recovered)

	// Output: 条目 failed(EXEC_TIMEOUT) + 告警通知。
	progress := h.MustProgress(orderID)
	require.Len(t, progress.ItemStates, 1)
	assert.Equal(t, string(domain.ItemStatusFailed), progress.ItemStates[0].Status)
	assert.Contains(t, progress.ItemStates[0].Error, "EXEC_TIMEOUT")
	require.Len(t, h.Notifier.Events(), 1, "executing-timeout notification published")
	assert.Equal(t, itemID, h.Notifier.Events()[0].ItemID)

	// State: 悬空映射保留为崩溃恢复锚点（未绑定产物等待收敛/覆盖）。
	anchor, err := h.MappingByCloudCert("huawei", "acct-hw-1", firstUploadID)
	require.NoError(t, err)
	assert.Equal(t, domain.MappingStatusActive, anchor.Status)

	// The recovery leaves the order verifying ( active mutex still held ).
	// 收敛到终态：窗口到期终局判定（生产入口 cert:window-expiry）。
	expired, err := h.Verify.FinalizeExpiredWindows(context.Background())
	require.NoError(t, err)
	require.Len(t, expired, 1)
	assert.Equal(t, orderID, expired[0])

	// 重跑：新执行重新走两段式上传新副本，按映射唯一键覆盖旧记录。
	newOrderID := h.SeedOrder(domain.ChangeStatusExecuting, seededBatchInfo(1), nil, w.OldFP, w.NewCertID)
	h.SeedItem(newOrderID, ref, domain.ItemStatusPending, 1, w.OldCloudIDs["huawei"])
	h.MustExecute(newOrderID)

	rerunUploads := h.Huawei.UploadCalls()
	require.Len(t, rerunUploads, 1, "rerun uploads a fresh copy (new name, not the dangling ID)")
	assert.NotEqual(t, firstUploadID, latestMappingID(t, h, w.NewFP),
		"mapping overwritten by the rerun upload (unique-key upsert, row count unchanged)")
	assert.Equal(t, string(domain.ItemStatusSuccess), h.MustProgress(newOrderID).ItemStates[0].Status)
}

// latestMappingID returns the cloudCertId of the single active mapping row
// for a fingerprint ( unique key => at most one row per cloud/account ).
func latestMappingID(t *testing.T, h *multicloudtest.Harness, fingerprint string) string {
	t.Helper()
	rows, err := h.Mappings.ListByFingerprint(context.Background(), fingerprint)
	require.NoError(t, err)
	require.Len(t, rows, 1, "unique-key upsert keeps exactly one mapping row: %d", len(rows))
	return rows[0].CloudCertID
}
