// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package endpoint

import (
	"github.com/Havens-blog/e-cam-service/internal/endpoint/internal/repository"
	"github.com/Havens-blog/e-cam-service/internal/endpoint/internal/repository/dao"
	"github.com/Havens-blog/e-cam-service/internal/endpoint/internal/service"
	"github.com/Havens-blog/e-cam-service/internal/endpoint/internal/web"
	"github.com/Havens-blog/e-cam-service/pkg/mongox"
	"github.com/google/wire"
	"sync"
)

// Injectors from wire.go:

func InitModule(db *mongox.Mongo) (*Module, error) {
	endpointDAO := InitEndpointDAO(db)
	endpointRepository := repository.NewEndpointRepository(endpointDAO)
	serviceService := service.NewService(endpointRepository)
	v := web.NewHandler(serviceService)
	module := &Module{
		Hdl: v,
		Svc: serviceService,
	}
	return module, nil
}

// wire.go:

var ProviderSet = wire.NewSet(web.NewHandler, service.NewService, repository.NewEndpointRepository)

var daoOnce = sync.Once{}

func InitCollectionOnce(db *mongox.Mongo) {
	daoOnce.Do(func() {
		err := dao.InitIndexes(db)
		if err != nil {
			panic(err)
		}
	})
}

func InitEndpointDAO(db *mongox.Mongo) dao.EndpointDAO {
	InitCollectionOnce(db)
	return dao.NewEndpointDAO(db)
}
